/**
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.iAmGroot.impl;

import edu.upb.lp.iAmGroot.AssignationValue;
import edu.upb.lp.iAmGroot.IAmGrootPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Assignation Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AssignationValueImpl extends MinimalEObjectImpl.Container implements AssignationValue
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AssignationValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IAmGrootPackage.Literals.ASSIGNATION_VALUE;
  }

} //AssignationValueImpl
