/**
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.iAmGroot.impl;

import edu.upb.lp.iAmGroot.IAmGrootPackage;
import edu.upb.lp.iAmGroot.InitializationNum;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Initialization Num</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InitializationNumImpl extends MinimalEObjectImpl.Container implements InitializationNum
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InitializationNumImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IAmGrootPackage.Literals.INITIALIZATION_NUM;
  }

} //InitializationNumImpl
