/*
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IAmGrootAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/upb/lp/parser/antlr/internal/InternalIAmGroot.tokens");
	}
}
