/*
 * generated by Xtext 2.31.0
 */
package edu.upb.lp;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class IAmGrootStandaloneSetup extends IAmGrootStandaloneSetupGenerated {

	public static void doSetup() {
		new IAmGrootStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
