/*
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIAmGrootScopeProvider extends DelegatingScopeProvider {
}
