/**
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.iAmGroot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignation Bool</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.iAmGroot.AssignationBool#getBoolean <em>Boolean</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getAssignationBool()
 * @model
 * @generated
 */
public interface AssignationBool extends InitializationBool, AssignationValue
{
  /**
   * Returns the value of the '<em><b>Boolean</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boolean</em>' attribute.
   * @see #setBoolean(String)
   * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getAssignationBool_Boolean()
   * @model
   * @generated
   */
  String getBoolean();

  /**
   * Sets the value of the '{@link edu.upb.lp.iAmGroot.AssignationBool#getBoolean <em>Boolean</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Boolean</em>' attribute.
   * @see #getBoolean()
   * @generated
   */
  void setBoolean(String value);

} // AssignationBool
