/**
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.iAmGroot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignation Num</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.iAmGroot.AssignationNum#getNumber <em>Number</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getAssignationNum()
 * @model
 * @generated
 */
public interface AssignationNum extends InitializationNum, AssignationValue
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getAssignationNum_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link edu.upb.lp.iAmGroot.AssignationNum#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

} // AssignationNum
