/**
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.iAmGroot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignation Str</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.iAmGroot.AssignationStr#getString <em>String</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getAssignationStr()
 * @model
 * @generated
 */
public interface AssignationStr extends InitializationStr, AssignationValue
{
  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getAssignationStr_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link edu.upb.lp.iAmGroot.AssignationStr#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

} // AssignationStr
