/**
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.iAmGroot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.iAmGroot.Assignation#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getAssignation()
 * @model
 * @generated
 */
public interface Assignation extends Sentence
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(AssignationValue)
   * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getAssignation_Value()
   * @model containment="true"
   * @generated
   */
  AssignationValue getValue();

  /**
   * Sets the value of the '{@link edu.upb.lp.iAmGroot.Assignation#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(AssignationValue value);

} // Assignation
