/**
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.iAmGroot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.iAmGroot.Declaration#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends Sentence
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(GrootTypes)
   * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getDeclaration_Type()
   * @model containment="true"
   * @generated
   */
  GrootTypes getType();

  /**
   * Sets the value of the '{@link edu.upb.lp.iAmGroot.Declaration#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(GrootTypes value);

} // Declaration
