/**
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.iAmGroot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Groot Types</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.iAmGroot.GrootTypes#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getGrootTypes()
 * @model
 * @generated
 */
public interface GrootTypes extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(EObject)
   * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getGrootTypes_Value()
   * @model containment="true"
   * @generated
   */
  EObject getValue();

  /**
   * Sets the value of the '{@link edu.upb.lp.iAmGroot.GrootTypes#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(EObject value);

} // GrootTypes
