/**
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.iAmGroot;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see edu.upb.lp.iAmGroot.IAmGrootPackage
 * @generated
 */
public interface IAmGrootFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IAmGrootFactory eINSTANCE = edu.upb.lp.iAmGroot.impl.IAmGrootFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Program</em>'.
   * @generated
   */
  Program createProgram();

  /**
   * Returns a new object of class '<em>Groot</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Groot</em>'.
   * @generated
   */
  Groot createGroot();

  /**
   * Returns a new object of class '<em>Sentence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sentence</em>'.
   * @generated
   */
  Sentence createSentence();

  /**
   * Returns a new object of class '<em>Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declaration</em>'.
   * @generated
   */
  Declaration createDeclaration();

  /**
   * Returns a new object of class '<em>Groot Types</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Groot Types</em>'.
   * @generated
   */
  GrootTypes createGrootTypes();

  /**
   * Returns a new object of class '<em>Initialization Num</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initialization Num</em>'.
   * @generated
   */
  InitializationNum createInitializationNum();

  /**
   * Returns a new object of class '<em>Initialization Str</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initialization Str</em>'.
   * @generated
   */
  InitializationStr createInitializationStr();

  /**
   * Returns a new object of class '<em>Initialization Bool</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initialization Bool</em>'.
   * @generated
   */
  InitializationBool createInitializationBool();

  /**
   * Returns a new object of class '<em>Assignation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignation</em>'.
   * @generated
   */
  Assignation createAssignation();

  /**
   * Returns a new object of class '<em>Assignation Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignation Value</em>'.
   * @generated
   */
  AssignationValue createAssignationValue();

  /**
   * Returns a new object of class '<em>Assignation Num</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignation Num</em>'.
   * @generated
   */
  AssignationNum createAssignationNum();

  /**
   * Returns a new object of class '<em>Assignation Str</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignation Str</em>'.
   * @generated
   */
  AssignationStr createAssignationStr();

  /**
   * Returns a new object of class '<em>Assignation Bool</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assignation Bool</em>'.
   * @generated
   */
  AssignationBool createAssignationBool();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  IAmGrootPackage getIAmGrootPackage();

} //IAmGrootFactory
