/**
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.iAmGroot;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.upb.lp.iAmGroot.IAmGrootFactory
 * @model kind="package"
 * @generated
 */
public interface IAmGrootPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "iAmGroot";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.upb.edu/lp/IAmGroot";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "iAmGroot";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IAmGrootPackage eINSTANCE = edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.ProgramImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Groots</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__GROOTS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.GrootImpl <em>Groot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.GrootImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getGroot()
   * @generated
   */
  int GROOT = 1;

  /**
   * The number of structural features of the '<em>Groot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROOT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.SentenceImpl <em>Sentence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.SentenceImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getSentence()
   * @generated
   */
  int SENTENCE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENTENCE__NAME = GROOT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sentence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENTENCE_FEATURE_COUNT = GROOT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.DeclarationImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__NAME = SENTENCE__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__TYPE = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.GrootTypesImpl <em>Groot Types</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.GrootTypesImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getGrootTypes()
   * @generated
   */
  int GROOT_TYPES = 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROOT_TYPES__VALUE = 0;

  /**
   * The number of structural features of the '<em>Groot Types</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROOT_TYPES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.InitializationNumImpl <em>Initialization Num</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.InitializationNumImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getInitializationNum()
   * @generated
   */
  int INITIALIZATION_NUM = 5;

  /**
   * The number of structural features of the '<em>Initialization Num</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIALIZATION_NUM_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.InitializationStrImpl <em>Initialization Str</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.InitializationStrImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getInitializationStr()
   * @generated
   */
  int INITIALIZATION_STR = 6;

  /**
   * The number of structural features of the '<em>Initialization Str</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIALIZATION_STR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.InitializationBoolImpl <em>Initialization Bool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.InitializationBoolImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getInitializationBool()
   * @generated
   */
  int INITIALIZATION_BOOL = 7;

  /**
   * The number of structural features of the '<em>Initialization Bool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIALIZATION_BOOL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.AssignationImpl <em>Assignation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.AssignationImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getAssignation()
   * @generated
   */
  int ASSIGNATION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNATION__NAME = SENTENCE__NAME;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNATION__VALUE = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Assignation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNATION_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.AssignationValueImpl <em>Assignation Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.AssignationValueImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getAssignationValue()
   * @generated
   */
  int ASSIGNATION_VALUE = 9;

  /**
   * The number of structural features of the '<em>Assignation Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNATION_VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.AssignationNumImpl <em>Assignation Num</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.AssignationNumImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getAssignationNum()
   * @generated
   */
  int ASSIGNATION_NUM = 10;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNATION_NUM__NUMBER = INITIALIZATION_NUM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Assignation Num</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNATION_NUM_FEATURE_COUNT = INITIALIZATION_NUM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.AssignationStrImpl <em>Assignation Str</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.AssignationStrImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getAssignationStr()
   * @generated
   */
  int ASSIGNATION_STR = 11;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNATION_STR__STRING = INITIALIZATION_STR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Assignation Str</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNATION_STR_FEATURE_COUNT = INITIALIZATION_STR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.iAmGroot.impl.AssignationBoolImpl <em>Assignation Bool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.iAmGroot.impl.AssignationBoolImpl
   * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getAssignationBool()
   * @generated
   */
  int ASSIGNATION_BOOL = 12;

  /**
   * The feature id for the '<em><b>Boolean</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNATION_BOOL__BOOLEAN = INITIALIZATION_BOOL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Assignation Bool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNATION_BOOL_FEATURE_COUNT = INITIALIZATION_BOOL_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see edu.upb.lp.iAmGroot.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.iAmGroot.Program#getGroots <em>Groots</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Groots</em>'.
   * @see edu.upb.lp.iAmGroot.Program#getGroots()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Groots();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.Groot <em>Groot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Groot</em>'.
   * @see edu.upb.lp.iAmGroot.Groot
   * @generated
   */
  EClass getGroot();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.Sentence <em>Sentence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sentence</em>'.
   * @see edu.upb.lp.iAmGroot.Sentence
   * @generated
   */
  EClass getSentence();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.iAmGroot.Sentence#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.iAmGroot.Sentence#getName()
   * @see #getSentence()
   * @generated
   */
  EAttribute getSentence_Name();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see edu.upb.lp.iAmGroot.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.iAmGroot.Declaration#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see edu.upb.lp.iAmGroot.Declaration#getType()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_Type();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.GrootTypes <em>Groot Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Groot Types</em>'.
   * @see edu.upb.lp.iAmGroot.GrootTypes
   * @generated
   */
  EClass getGrootTypes();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.iAmGroot.GrootTypes#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see edu.upb.lp.iAmGroot.GrootTypes#getValue()
   * @see #getGrootTypes()
   * @generated
   */
  EReference getGrootTypes_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.InitializationNum <em>Initialization Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initialization Num</em>'.
   * @see edu.upb.lp.iAmGroot.InitializationNum
   * @generated
   */
  EClass getInitializationNum();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.InitializationStr <em>Initialization Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initialization Str</em>'.
   * @see edu.upb.lp.iAmGroot.InitializationStr
   * @generated
   */
  EClass getInitializationStr();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.InitializationBool <em>Initialization Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initialization Bool</em>'.
   * @see edu.upb.lp.iAmGroot.InitializationBool
   * @generated
   */
  EClass getInitializationBool();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.Assignation <em>Assignation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignation</em>'.
   * @see edu.upb.lp.iAmGroot.Assignation
   * @generated
   */
  EClass getAssignation();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.iAmGroot.Assignation#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see edu.upb.lp.iAmGroot.Assignation#getValue()
   * @see #getAssignation()
   * @generated
   */
  EReference getAssignation_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.AssignationValue <em>Assignation Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignation Value</em>'.
   * @see edu.upb.lp.iAmGroot.AssignationValue
   * @generated
   */
  EClass getAssignationValue();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.AssignationNum <em>Assignation Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignation Num</em>'.
   * @see edu.upb.lp.iAmGroot.AssignationNum
   * @generated
   */
  EClass getAssignationNum();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.iAmGroot.AssignationNum#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see edu.upb.lp.iAmGroot.AssignationNum#getNumber()
   * @see #getAssignationNum()
   * @generated
   */
  EAttribute getAssignationNum_Number();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.AssignationStr <em>Assignation Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignation Str</em>'.
   * @see edu.upb.lp.iAmGroot.AssignationStr
   * @generated
   */
  EClass getAssignationStr();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.iAmGroot.AssignationStr#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see edu.upb.lp.iAmGroot.AssignationStr#getString()
   * @see #getAssignationStr()
   * @generated
   */
  EAttribute getAssignationStr_String();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.iAmGroot.AssignationBool <em>Assignation Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignation Bool</em>'.
   * @see edu.upb.lp.iAmGroot.AssignationBool
   * @generated
   */
  EClass getAssignationBool();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.iAmGroot.AssignationBool#getBoolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Boolean</em>'.
   * @see edu.upb.lp.iAmGroot.AssignationBool#getBoolean()
   * @see #getAssignationBool()
   * @generated
   */
  EAttribute getAssignationBool_Boolean();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IAmGrootFactory getIAmGrootFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.ProgramImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Groots</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__GROOTS = eINSTANCE.getProgram_Groots();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.GrootImpl <em>Groot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.GrootImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getGroot()
     * @generated
     */
    EClass GROOT = eINSTANCE.getGroot();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.SentenceImpl <em>Sentence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.SentenceImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getSentence()
     * @generated
     */
    EClass SENTENCE = eINSTANCE.getSentence();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENTENCE__NAME = eINSTANCE.getSentence_Name();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.DeclarationImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__TYPE = eINSTANCE.getDeclaration_Type();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.GrootTypesImpl <em>Groot Types</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.GrootTypesImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getGrootTypes()
     * @generated
     */
    EClass GROOT_TYPES = eINSTANCE.getGrootTypes();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROOT_TYPES__VALUE = eINSTANCE.getGrootTypes_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.InitializationNumImpl <em>Initialization Num</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.InitializationNumImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getInitializationNum()
     * @generated
     */
    EClass INITIALIZATION_NUM = eINSTANCE.getInitializationNum();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.InitializationStrImpl <em>Initialization Str</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.InitializationStrImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getInitializationStr()
     * @generated
     */
    EClass INITIALIZATION_STR = eINSTANCE.getInitializationStr();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.InitializationBoolImpl <em>Initialization Bool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.InitializationBoolImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getInitializationBool()
     * @generated
     */
    EClass INITIALIZATION_BOOL = eINSTANCE.getInitializationBool();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.AssignationImpl <em>Assignation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.AssignationImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getAssignation()
     * @generated
     */
    EClass ASSIGNATION = eINSTANCE.getAssignation();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNATION__VALUE = eINSTANCE.getAssignation_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.AssignationValueImpl <em>Assignation Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.AssignationValueImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getAssignationValue()
     * @generated
     */
    EClass ASSIGNATION_VALUE = eINSTANCE.getAssignationValue();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.AssignationNumImpl <em>Assignation Num</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.AssignationNumImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getAssignationNum()
     * @generated
     */
    EClass ASSIGNATION_NUM = eINSTANCE.getAssignationNum();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGNATION_NUM__NUMBER = eINSTANCE.getAssignationNum_Number();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.AssignationStrImpl <em>Assignation Str</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.AssignationStrImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getAssignationStr()
     * @generated
     */
    EClass ASSIGNATION_STR = eINSTANCE.getAssignationStr();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGNATION_STR__STRING = eINSTANCE.getAssignationStr_String();

    /**
     * The meta object literal for the '{@link edu.upb.lp.iAmGroot.impl.AssignationBoolImpl <em>Assignation Bool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.iAmGroot.impl.AssignationBoolImpl
     * @see edu.upb.lp.iAmGroot.impl.IAmGrootPackageImpl#getAssignationBool()
     * @generated
     */
    EClass ASSIGNATION_BOOL = eINSTANCE.getAssignationBool();

    /**
     * The meta object literal for the '<em><b>Boolean</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGNATION_BOOL__BOOLEAN = eINSTANCE.getAssignationBool_Boolean();

  }

} //IAmGrootPackage
