/**
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.iAmGroot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Initialization Bool</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.iAmGroot.IAmGrootPackage#getInitializationBool()
 * @model
 * @generated
 */
public interface InitializationBool extends EObject
{
} // InitializationBool
