/*
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.ui;

import com.google.inject.Injector;
import iamgroot.ui.internal.IamgrootActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IAmGrootExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(IamgrootActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		IamgrootActivator activator = IamgrootActivator.getInstance();
		return activator != null ? activator.getInjector(IamgrootActivator.EDU_UPB_LP_IAMGROOT) : null;
	}

}
