/*
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IAmGrootUiModule extends AbstractIAmGrootUiModule {

	public IAmGrootUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
