/*
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.serializer;

import com.google.inject.Inject;
import edu.upb.lp.services.IAmGrootGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class IAmGrootSyntacticSequencer extends AbstractSyntacticSequencer {

	protected IAmGrootGrammarAccess grammarAccess;
	protected AbstractElementAlias match_GrootTypes_BooltKeyword_2_1_or_NumbootKeyword_0_1_or_StrootKeyword_1_1;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (IAmGrootGrammarAccess) access;
		match_GrootTypes_BooltKeyword_2_1_or_NumbootKeyword_0_1_or_StrootKeyword_1_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getGrootTypesAccess().getBooltKeyword_2_1()), new TokenAlias(false, false, grammarAccess.getGrootTypesAccess().getNumbootKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getGrootTypesAccess().getStrootKeyword_1_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_GrootTypes_BooltKeyword_2_1_or_NumbootKeyword_0_1_or_StrootKeyword_1_1.equals(syntax))
				emit_GrootTypes_BooltKeyword_2_1_or_NumbootKeyword_0_1_or_StrootKeyword_1_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'Numboot' | 'Stroot' | 'Boolt'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_GrootTypes_BooltKeyword_2_1_or_NumbootKeyword_0_1_or_StrootKeyword_1_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
