/*
 * generated by Xtext 2.31.0
 */
package edu.upb.lp.ui.tests;

import com.google.inject.Injector;
import iamgroot.ui.internal.IamgrootActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IAmGrootUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IamgrootActivator.getInstance().getInjector("edu.upb.lp.IAmGroot");
	}

}
